DEBUG = FALSE

DIM = 2

USE_MPI = TRUE
USE_OMP = FALSE

USE_CUDA  = FALSE
USE_HIP   = FALSE
USE_SYCL  = FALSE

#No Fortran
BL_NO_FORT = TRUE
# No Fortran probin file
AMREX_NO_PROBINIT = TRUE

CXXSTD=c++17

include ./Make.package
include ../Make.QGD
